### PR TITLE
chore: enable fail on warning

### PR DESCRIPTION
**Pull request by bollu**
This forces us to fix all warnings.

### CODE REVIEW

**Comment by bollu** [comment]
we need to figure out what to do with sorrys

**Comment by tobiasgrosser** [comment]
We only have two sorries left in proofs that we may not need. Should we just drop them and replace them with `proofwanted`? This this PR can go in.

**Comment by bollu** [comment]
@tobiasgrosser that's a good idea, would you mind making the change?

**Comment by tobiasgrosser** [comment]
> @tobiasgrosser that's a good idea, would you mind making the change?

I replaced the first: https://github.com/opencompl/ssa/pull/363.

Not sure what about the second one. Should we comment that one?

**Comment by tobiasgrosser** [comment]
I commented the last sorry. Let's see if that makes this PR green.

**Comment by tobiasgrosser** [comment]
This did not make it for months. Let's close it for now.

**Pull request closed without merging**
