### PR TITLE
chore: update nightly-testing-2024-12-11

### PR DESCRIPTION
**Pull request by luisacicolini**

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
Thank you for the update.

**Comment by luisacicolini** [comment]
@ineol I think I need again your support for this: there are some errors in `ForMathlib` in autostructs and I am struggling to fix them :(

**Comment by ineol** [comment]
@luisacicolini on it!

**Comment by ineol** [comment]
It should work now

**Comment by luisacicolini** [comment]
perfect, thank you!!

**Pull request merged**
