### PR TITLE
Faster version of the bitvector decision procedure

### PR DESCRIPTION
**Pull request by ChrisHughes24**
This depends on a mathlib PR that isn't merged yet, so maybe we should wait.

### CODE REVIEW

**Comment by bollu** [comment]
@ChrisHughes24 could you change the mathlib version to be the same as master?

**Comment by ChrisHughes24** [comment]
This PR depends on a branch of mathlib so not right now. When the branch is merged then maybe.

**Comment by bollu** [comment]
@ChrisHughes24 could you meassage again on this thread when you have synchronized the changes post mathlib merge? That way, I'll know when this can be merged :)

**Comment by goens** [comment]
have the changes to Mathlib been merged? @ChrisHughes24

**Comment by ChrisHughes24** [comment]
No

**Comment by tobiasgrosser** [comment]
It seems the mathlib PR this depends on has still not been merged: https://github.com/leanprover-community/mathlib4/pull/5549

**Comment by tobiasgrosser** [comment]
Close this to archive it for historical purposes. The rebased PR is at https://github.com/opencompl/lean-mlir/pull/425.

**Pull request closed without merging**
