### PR TITLE
inspiration: two more theorem classes

### PR DESCRIPTION
**Pull request by tobiasgrosser**

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
@AtticusKuhn, I feel these two theorem classes can be further generalized to (a) make this build green and (b) cover a lot more of the `ofBool` lemmas

**Comment by tobiasgrosser** [comment]
@bollu suggests to make the decide move a simp-proc. @AtticusKuhn, check with @bollu on this.

**Comment by AtticusKuhn** [comment]
Sounds good. I will look into `simproc`s.

**Comment by AtticusKuhn** [comment]
Why is a simproc neccessary in this case?

Shouldn't `bv_ofBool` also solve it?

The example given above is also solved by 

```lean4
theorem bitvec_AndOrXor_1683_1 :
    ∀ (e e_1 : LLVM.IntW w),
      LLVM.or (LLVM.icmp LLVM.IntPredicate.ugt e_1 e) (LLVM.icmp LLVM.IntPredicate.eq e_1 e) ⊑
        LLVM.icmp LLVM.IntPredicate.uge e_1 e := by
  simp_alive_undef
  simp_alive_ops
  simp_alive_case_bash
  try alive_auto
  simp [bv_ofBool]
  simp [aaa]
```

This is because

```lean4
@[bv_ofBool]
theorem ofBool_or {a b : Bool} : BitVec.ofBool a ||| BitVec.ofBool b = ofBool (a || b) := by
  simp [bv_toNat]; rcases a <;> rcases b <;> rfl

@[bv_ofBool]
theorem ofBool_and {a b : Bool} : BitVec.ofBool a &&& BitVec.ofBool b = ofBool (a && b) := by
  simp [bv_toNat]; rcases a <;> rcases b <;> rfl

@[bv_ofBool]
theorem ofBool_xor {a b : Bool} : BitVec.ofBool a ^^^ BitVec.ofBool b = ofBool (a.xor b) := by
  simp [bv_toNat]; rcases a <;> rcases b <;> rfl
```

**Comment by AtticusKuhn** [comment]
I feel like the simplest solution would be to do something like


```lean
macro "ofBoolTactic" : tactic =>
  `(tactic|
    (
      repeat (
        first
      | simp [bv_ofBool]
      | simp [ofBool_eq']
      | simp
      | simp only [bne]
      )
      repeat (
        first
      | simp only [BitVec.ule]
      | simp only [BitVec.ult]
      | simp only [BEq.beq]
      | simp only [← Bool.decide_or]
      | simp only [← decide_not]
      | simp only [decide_eq_decide]
      | simp [of_decide_eq_true]
      | simp only [BitVec.toNat_eq]
      )
      try omega
    )
  )
```

**Comment by AtticusKuhn** [comment]
The of_bool tactic solves 2 of the alive statements. It could possibly solve more.

**Review by AtticusKuhn — APPROVED** [review]
Code seems good to me.

**Pull request merged**
