### PR TITLE
chore: update nightly-testing-2024-12-09

### PR DESCRIPTION
**Pull request by luisacicolini**

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
This seems good to go, no?

**Comment by luisacicolini** [comment]
i commented some of @ineol's code, I would like to amke sure that it did not impair too much of his work (+ I commented a test in alive that is not yet fixed)

**Comment by luisacicolini** [comment]
@ineol in particular the `corr` tactic in `Constructions` seems problematic and I can't seem to find a way out. If you could take a look it would be super helpful, otherwise I'm happy to comment and merge.

**Comment by ineol** [comment]
@luisacicolini I removed these proofs, they will be completely changed by a PR soon

**Comment by luisacicolini** [comment]
perfect, thank you @ineol. Will merge the PR as soon as CI is done.

**Pull request merged**
