### PR TITLE
chore: update mathlib 2024-10-19

### PR DESCRIPTION
**Pull request by luisacicolini**

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
> error: ././././SSA/Projects/Scf/ScfFunctor.lean:491:2: failed to construct new type correct motive for `Eq.ndrec` while creating splitter/eliminator theorem for `ScfFunctor.Scf.instDialectDenoteOfMonadM.match_1`

There seems to be a regression in lean? @bollu is this sth worth reporting?

**Comment by luisacicolini** [comment]
@tobiasgrosser thank you for this! should I continue with the latest update on this branch if this builds?

**Comment by tobiasgrosser** [comment]
Let's just merge this and create an issue that maybe @bollu or @alexkeizer can help us reduce?

**Comment by tobiasgrosser** [comment]
> @tobiasgrosser thank you for this! should I continue with the latest update on this branch if this builds?

If you could then do another update to the latest version, that would be great.

**Comment by tobiasgrosser** [comment]
It seems our scaling tests also fail. 😢

**Comment by luisacicolini** [comment]
do we have any idea why is that? is it something I could look into?

**Comment by tobiasgrosser** [comment]
This is a significant pain. 😢 Let's discuss with Sid and alex today.

**Comment by tobiasgrosser** [comment]
I don't think you can debug this effectively.

**Pull request merged**
