### PR TITLE
Update README with new title, logo in the title bar, and mildly amended description

### PR DESCRIPTION
**Pull request by bollu**

### CODE REVIEW

**Comment by alexkeizer** [comment]
I wouldn't use pixel sizes, see https://github.com/opencompl/lean-mlir/pull/404 for a responsive way to resize the image

**Comment by goens** [comment]
lgtm

**Comment by bollu** [comment]
@alexkeizer certainly, happy to use `vh`.

**Comment by bollu** [comment]
Thanks @alexkeizer , switched to using `vh`.

**Comment by alexkeizer** [comment]
> @alexkeizer certainly, happy to use `vh`.

You could also use `em`, which refers to the standard font size and might be more appropriate here since you're making it part of the header

**Pull request merged**
